"use client";

import { useEffect, useState } from "react";
import { Dataset, datasetsApi } from "../services/api";

export function AnalyticsWorkspace() {
  const [datasets, setDatasets] = useState<Dataset[]>([]); const [dataset, setDataset] = useState<Dataset>(); const [measure, setMeasure] = useState(""); const [dimension, setDimension] = useState(""); const [result, setResult] = useState<{ kpi: number; breakdown: Record<string, unknown>[]; trend: Record<string, unknown>[] }>();
  useEffect(() => { datasetsApi.list().then(setDatasets).catch(() => undefined); }, []);
  const columns = Object.keys(((dataset?.profile?.columns ?? {}) as Record<string, Record<string, unknown>>)); const numeric = columns.filter((name) => ((dataset?.profile?.columns as Record<string, Record<string, unknown>>)?.[name]?.type === "numeric"));
  const run = async () => { if (!dataset || !measure) return; setResult(await datasetsApi.analytics(dataset.id, { measure, dimension: dimension || undefined, aggregation: "sum" })); };
  return <div className="space-y-6"><div><h1 className="text-3xl font-semibold">Analytics</h1><p className="mt-2 text-slate-400">Descriptive analysis only; correlations are not causal evidence.</p></div><div className="flex flex-wrap gap-3 rounded-xl border border-slate-800 p-4"><select onChange={async (e) => { const found = datasets.find((item) => item.id === e.target.value); if (found) setDataset(await datasetsApi.details(found.id)); }} defaultValue=""><option value="">Select dataset</option>{datasets.map((item) => <option key={item.id} value={item.id}>{item.original_filename}</option>)}</select><select value={measure} onChange={(e) => setMeasure(e.target.value)}><option value="">Measure</option>{numeric.map((name) => <option key={name}>{name}</option>)}</select><select value={dimension} onChange={(e) => setDimension(e.target.value)}><option value="">Dimension (optional)</option>{columns.map((name) => <option key={name}>{name}</option>)}</select><button onClick={run} className="rounded bg-cyan-700 px-4 py-2 text-sm">Run analysis</button></div>{result && <><section className="rounded-xl border border-slate-800 p-5"><p className="text-sm text-slate-400">KPI · sum</p><p className="text-3xl font-semibold">{result.kpi.toLocaleString()}</p></section><section className="rounded-xl border border-slate-800 p-4"><h2 className="font-medium">Category breakdown / distribution</h2><div className="mt-3 space-y-2">{result.breakdown.map((row, index) => <div key={index} className="flex gap-3 text-sm"><span className="w-40 truncate">{String(Object.values(row)[0])}</span><div className="h-5 bg-cyan-700" style={{ width: `${Math.min(100, Number(row.value) / Math.max(...result.breakdown.map((item) => Number(item.value))) * 100)}%` }} /><span>{Number(row.value).toLocaleString()}</span></div>)}</div></section>{dataset?.profile?.correlation && <section className="rounded-xl border border-slate-800 p-4"><h2 className="font-medium">Correlation matrix</h2><pre className="mt-3 overflow-auto text-xs text-slate-300">{JSON.stringify(dataset.profile.correlation, null, 2)}</pre></section>}</>}</div>;
}
