"use client";

import { ChangeEvent, useCallback, useEffect, useRef, useState } from "react";
import { Dataset, datasetsApi } from "../services/api";

type Preview = { columns: string[]; rows: Record<string, unknown>[] };
type Connection = "checking" | "online" | "offline";

function uploadMessage(error: unknown) { const detail = error instanceof Error ? error.message : ""; if (detail.includes("415")) return "Choose a CSV, XLS, or XLSX file."; if (detail.includes("422")) return "This file could not be read. Check its format and try again."; return "The upload could not be completed. Please try again."; }

export function DataWorkspace() {
  const [datasets, setDatasets] = useState<Dataset[]>([]); const [selected, setSelected] = useState<Dataset>(); const [preview, setPreview] = useState<Preview>(); const [connection, setConnection] = useState<Connection>("checking"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [isLoading, setIsLoading] = useState(true); const [isUploading, setIsUploading] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const refresh = useCallback(async () => { const items = await datasetsApi.list(); setDatasets(items); setConnection("online"); }, []);
  const retry = useCallback(async () => { setIsLoading(true); try { await refresh(); } catch { setConnection("offline"); } finally { setIsLoading(false); } }, [refresh]);
  useEffect(() => { void retry(); }, [retry]);
  const choose = async (item: Dataset) => { setError(""); try { const [details, table] = await Promise.all([datasetsApi.details(item.id), datasetsApi.preview(item.id)]); setSelected(details); setPreview(table); } catch { setError("We could not load this dataset profile. Please try again."); } };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(""); setNotice(""); setIsUploading(true); try { const uploaded = await datasetsApi.upload(file); await refresh(); await choose(uploaded); setNotice(`${uploaded.original_filename} has been profiled and is ready for analysis.`); } catch (reason) { setError(uploadMessage(reason)); } finally { setIsUploading(false); event.target.value = ""; } };
  const columns = (selected?.profile?.columns ?? {}) as Record<string, Record<string, unknown>>;
  return <div className="space-y-7"><section className="page-hero"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">DATA FOUNDATION</p><h1>Build a trusted data workspace.</h1><p>Bring in your source data once. NEXORA profiles its structure, quality, and coverage before any analysis begins.</p></div><div className="rounded-lg border border-white/20 bg-white/10 px-4 py-3 text-sm text-white"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${connection === "online" ? "bg-emerald-300" : "bg-amber-300"}`} />{connection === "online" ? "Data service connected" : connection === "checking" ? "Checking data service" : "Data service offline"}</div></div></section>
    {connection === "offline" && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Data service is not running.</b> Start the backend on port 8000, then <button type="button" className="ml-2 font-bold underline" onClick={() => void retry()}>retry the connection</button>.</div>}
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="panel"><p className="eyebrow !text-teal-700">SOURCE DATA</p><h2 className="panel-title mt-2 text-xl">Upload a dataset</h2><p className="panel-copy">CSV and Excel files are supported. The original file remains unchanged while the platform creates a traceable evidence profile.</p><div className="mt-6 flex flex-wrap items-center gap-3"><button type="button" className="primary-button" disabled={connection !== "online" || isUploading} onClick={() => inputRef.current?.click()}>{isUploading ? "Profiling file..." : "Choose data file"}</button><span className="text-sm text-slate-500">CSV, XLS, XLSX</span></div><input ref={inputRef} className="sr-only" type="file" accept=".csv,.xls,.xlsx" onChange={upload} />{notice && <p className="mt-5 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-800">{notice}</p>}{error && <p className="mt-5 rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-800">{error}</p>}</article><article className="panel"><p className="eyebrow !text-teal-700">WORKSPACE</p><div className="metric-value">{datasets.length}</div><p className="metric-note">dataset{datasets.length === 1 ? "" : "s"} available for evidence review</p><div className="mt-6 border-t border-slate-200 pt-4 text-sm leading-6 text-slate-600">Every displayed metric is computed from an uploaded source and can be traced back to it.</div></article></section>
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="panel"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow !text-teal-700">DATA LIBRARY</p><h2 className="panel-title mt-1 text-xl">Workspace datasets</h2><p className="panel-copy">Choose a dataset to open its evidence profile.</p></div>{isLoading && <span className="text-sm text-slate-400">Loading...</span>}</div><div className="mt-5 space-y-2">{!isLoading && datasets.length === 0 && <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-5 py-9 text-center text-sm text-slate-500">No source data yet. Upload a file above to begin the workflow.</div>}{datasets.map((item) => <button key={item.id} type="button" onClick={() => void choose(item)} className={`flex w-full items-center justify-between gap-4 rounded-lg border px-4 py-3 text-left transition ${selected?.id === item.id ? "border-teal-400 bg-teal-50" : "border-slate-200 bg-white hover:border-teal-300"}`}><span className="min-w-0"><span className="block truncate font-bold text-slate-800">{item.original_filename}</span><span className="mt-1 block text-xs text-slate-500">{item.row_count.toLocaleString()} rows / {item.column_count} columns</span></span><span className="shrink-0 rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800">{item.quality_score}% quality</span></button>)}</div></article><article className="panel"><p className="eyebrow !text-teal-700">EVIDENCE PROFILE</p>{selected ? <><div className="metric-value text-teal-700">{selected.quality_score}%</div><p className="metric-note">computed data quality score</p><dl className="mt-6 grid grid-cols-3 gap-2 border-t border-slate-200 pt-5 text-center"><div><dt className="text-xs text-slate-500">Rows</dt><dd className="mt-1 font-extrabold">{selected.row_count.toLocaleString()}</dd></div><div><dt className="text-xs text-slate-500">Columns</dt><dd className="mt-1 font-extrabold">{selected.column_count}</dd></div><div><dt className="text-xs text-slate-500">Duplicates</dt><dd className="mt-1 font-extrabold">{Number(selected.profile?.duplicate_count ?? 0).toLocaleString()}</dd></div></dl></> : <div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-600">Select a dataset to see its computed data quality, schema, missing values, and source preview.</div>}</article></section>
    {selected && <section className="panel overflow-hidden !p-0"><div className="border-b border-slate-200 px-5 py-4"><p className="eyebrow !text-teal-700">STRUCTURE</p><h2 className="panel-title mt-1">Columns and data coverage</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-slate-800 text-xs uppercase tracking-wide text-white"><tr><th className="px-5 py-3">Column</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Missing</th><th className="px-5 py-3">Unique</th></tr></thead><tbody>{Object.entries(columns).map(([name, info]) => <tr key={name} className="border-b border-slate-100"><td className="px-5 py-3 font-bold">{name}</td><td className="px-5 py-3 text-slate-600">{String(info.type)}</td><td className="px-5 py-3 text-slate-600">{String(info.missing_count)} ({String(info.missing_percent)}%)</td><td className="px-5 py-3 text-slate-600">{String(info.unique_count)}</td></tr>)}</tbody></table></div></section>}
    {preview && <section className="panel overflow-hidden !p-0"><div className="border-b border-slate-200 px-5 py-4"><p className="eyebrow !text-teal-700">SOURCE PREVIEW</p><h2 className="panel-title mt-1">Original values</h2><p className="panel-copy">First {preview.rows.length} rows, displayed without modifications.</p></div><div className="overflow-x-auto"><table className="w-full min-w-max text-left text-sm"><thead className="bg-slate-800 text-xs uppercase tracking-wide text-white"><tr>{preview.columns.map((column) => <th key={column} className="px-5 py-3">{column}</th>)}</tr></thead><tbody>{preview.rows.map((row, index) => <tr key={index} className="border-b border-slate-100">{preview.columns.map((column) => <td key={column} className="max-w-64 truncate whitespace-nowrap px-5 py-3 text-slate-600">{String(row[column] ?? "-")}</td>)}</tr>)}</tbody></table></div></section>}
  </div>;
}
