"use client";

import { useEffect, useState } from "react";
import { Decision, decisionsApi, InvestigatorResponse } from "../services/api";

export function InvestigatorWorkspace() {
  const [question, setQuestion] = useState("Why is this maintenance decision supported?"), [decisions, setDecisions] = useState<Decision[]>([]), [decisionId, setDecisionId] = useState("");
  const [result, setResult] = useState<InvestigatorResponse>(), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  useEffect(() => { decisionsApi.list().then((items) => { setDecisions(items); setDecisionId(items[0]?.id ?? ""); }).catch(() => setError("Decision evidence could not be loaded.")); }, []);
  async function submit() { if (!decisionId || !question.trim()) return; setLoading(true); setError(""); try { setResult(await decisionsApi.investigate(question.trim(), [], decisionId)); } catch { setError("The investigator could not ground an answer in this decision."); } finally { setLoading(false); } }
  return <div className="space-y-7"><section className="page-hero"><p className="eyebrow">EVIDENCE-BOUNDED INVESTIGATOR</p><h1>Ask why a recorded decision is supported.</h1><p>The investigator can summarize only evidence already attached to the selected decision. It cannot calculate new metrics or replace abstained recommendations.</p></section>{error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}<section className="panel"><div className="grid gap-3 md:grid-cols-[.7fr_1.3fr]"><label className="text-xs font-bold uppercase text-slate-600">Decision<select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" value={decisionId} onChange={(event) => setDecisionId(event.target.value)}><option value="">Select decision</option>{decisions.map((decision) => <option key={decision.id} value={decision.id}>{decision.reliability_status} · {decision.question}</option>)}</select></label><label className="text-xs font-bold uppercase text-slate-600">Question<textarea rows={3} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" value={question} onChange={(event) => setQuestion(event.target.value)} /></label></div><button disabled={!decisionId || !question.trim() || loading} onClick={() => void submit()} className="primary-button mt-4">{loading ? "Tracing evidence..." : "Investigate selected decision"}</button></section>{result && <section className="panel"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow !text-teal-700">GROUNDED RESPONSE</p><h2 className="panel-title mt-2">{result.intent} investigation</h2></div><span className="rounded bg-slate-800 px-2 py-1 text-xs font-bold text-white">{result.status}</span></div><p className="mt-5 text-lg leading-8 text-slate-800">{result.answer}</p><h3 className="mt-6 font-bold">Persisted evidence references</h3><div className="mt-3 space-y-2">{result.evidence.map((item) => <details key={item.id} className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-bold">{item.type} · {item.id}</summary><pre className="mt-2 overflow-x-auto rounded bg-slate-900 p-3 text-xs text-slate-100">{JSON.stringify(item.payload, null, 2)}</pre></details>)}</div></section>}</div>;
}
