"use client";
import { useEffect, useState } from "react";
import { Dataset, datasetsApi } from "../services/api";
import { FaultModelWorkspace } from "./fault-model-workspace";

export function MLLab() {
  const [data, setData] = useState<Dataset[]>([]), [dataset, setDataset] = useState<Dataset>(), [task, setTask] = useState("regression"), [target, setTarget] = useState(""), [result, setResult] = useState<Record<string, unknown>>();
  useEffect(() => { datasetsApi.list().then(setData); }, []);
  const columns = Object.keys((dataset?.profile?.columns ?? {}) as Record<string, unknown>);
  const train = async () => { if (!dataset) return; const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/api/datasets/${dataset.id}/ml-runs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ task, target: target || null, features: columns.filter((c) => c !== target) }) }); setResult((await response.json()).results); };
  return <div className="space-y-7"><section className="page-hero"><p className="eyebrow">PATTERN RECOGNITION</p><h1>Train models from traceable evidence.</h1><p>Compare fault classifiers on confirmed physical windows while keeping predictions separate from calibrated decisions and causal conclusions.</p></section><FaultModelWorkspace /><section className="panel"><p className="eyebrow !text-teal-700">GENERAL DATASET LAB</p><h2 className="panel-title mt-2">Uploaded-dataset experiments</h2><div className="mt-4 flex flex-wrap gap-3"><select onChange={async e => { const item = data.find(d => d.id === e.target.value); if (item) setDataset(await datasetsApi.details(item.id)); }}><option>Select dataset</option>{data.map(d => <option value={d.id} key={d.id}>{d.original_filename}</option>)}</select><select value={task} onChange={e => setTask(e.target.value)}>{["regression", "binary_classification", "multiclass_classification", "clustering", "anomaly_detection", "forecasting"].map(x => <option key={x}>{x}</option>)}</select>{!task.includes("clustering") && !task.includes("anomaly") && <select value={target} onChange={e => setTarget(e.target.value)}><option value="">Target</option>{columns.map(c => <option key={c}>{c}</option>)}</select>}<button className="primary-button" onClick={train}>Train dataset model</button></div>{result && <pre className="mt-4 overflow-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">{JSON.stringify(result, null, 2)}</pre>}</section></div>;
}
